//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransrateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyBackup
    {
        public string StaffID { get; set; }
        public int ApplyID { get; set; }
        public string ProjectName { get; set; }
        public string Members { get; set; }
        public string BackupFolderPath { get; set; }
        public System.DateTime LeadTime { get; set; }
    }
}
