//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransrateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyManage
    {
        public string StaffID { get; set; }
        public int ApplyID { get; set; }
        public int ApplyTypeID { get; set; }
        public int ApplyMethodID { get; set; }
        public int ApplyStatusID { get; set; }
        public string Boss_StaffID { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public string ApplyCode { get; set; }
    }
}
