//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransrateData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeManageEntities : DbContext
    {
        public OfficeManageEntities()
            : base("name=OfficeManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplyAccount> ApplyAccount { get; set; }
        public virtual DbSet<ApplyBackup> ApplyBackup { get; set; }
        public virtual DbSet<ApplyException> ApplyException { get; set; }
        public virtual DbSet<ApplyMailingList> ApplyMailingList { get; set; }
        public virtual DbSet<ApplyManage> ApplyManage { get; set; }
        public virtual DbSet<ApplyServer> ApplyServer { get; set; }
        public virtual DbSet<ApplyVPN> ApplyVPN { get; set; }
        public virtual DbSet<ApplyWireless> ApplyWireless { get; set; }
        public virtual DbSet<MST_Animal> MST_Animal { get; set; }
        public virtual DbSet<MST_ApplyMethod> MST_ApplyMethod { get; set; }
        public virtual DbSet<MST_ApplyStatus> MST_ApplyStatus { get; set; }
        public virtual DbSet<MST_ApplyType> MST_ApplyType { get; set; }
        public virtual DbSet<MST_AuthLevel> MST_AuthLevel { get; set; }
        public virtual DbSet<MST_BloodType> MST_BloodType { get; set; }
        public virtual DbSet<MST_Company> MST_Company { get; set; }
        public virtual DbSet<MST_Department1> MST_Department1 { get; set; }
        public virtual DbSet<MST_Department2> MST_Department2 { get; set; }
        public virtual DbSet<MST_Department3> MST_Department3 { get; set; }
        public virtual DbSet<MST_Post> MST_Post { get; set; }
        public virtual DbSet<PersonalInfo> PersonalInfo { get; set; }
        public virtual DbSet<StaffInfo> StaffInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
