//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransrateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public string StaffID { get; set; }
        public string CompanyName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string LastName_Kana { get; set; }
        public string FirstName_Kana { get; set; }
        public string ZipCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Tel_Personal1 { get; set; }
        public string Tel_Personal2 { get; set; }
        public string Tel_Personal3 { get; set; }
        public string Tel_Company1 { get; set; }
        public string Tel_Company2 { get; set; }
        public string Tel_Company3 { get; set; }
        public string Email { get; set; }
        public string Birthday_Year { get; set; }
        public string Birthday_Month { get; set; }
        public string Birthday_Day { get; set; }
        public Nullable<int> BloodTypeID { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public string BirthPlace { get; set; }
        public string Motto { get; set; }
    }
}
