//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransrateData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInfo
    {
        public string StaffID { get; set; }
        public int StaffNumber { get; set; }
        public Nullable<int> Department1ID { get; set; }
        public Nullable<int> Department2ID { get; set; }
        public Nullable<int> Department3ID { get; set; }
        public int PostID { get; set; }
        public int Period { get; set; }
        public int AuthLevel { get; set; }
        public string Club { get; set; }
        public string Password { get; set; }
    }
}
